import { Public_Sans } from "next/font/google";

import "../globals.css";

const font = Public_Sans({ subsets: ["latin"], weight: ["300", "400", "700"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={font.className}>
				<h1 className="clipped">Easybank</h1>
				{children}
			</body>
		</html>
	);
}
