import NavBar from "@component/components/NavBar/NavBar";
import { Public_Sans } from "next/font/google";

import "../globals.css";
import Footer from "@component/components/Footer/Footer";

const font = Public_Sans({ subsets: ["latin"], weight: ["300", "400", "700"] });

export const metadata = {
	title: "Easybank",
	description: "Generated by create next app",
};

const socialMedia = [
	{
		href: "https://es-la.facebook.com/",
		media: "facebook",
		icon: "/icon-facebook.svg",
	},
	{
		href: "https://www.youtube.com/",
		media: "youtube",
		icon: "/icon-youtube.svg",
	},
	{
		href: "https://twitter.com/",
		media: "twitter",
		icon: "/icon-twitter.svg",
	},
	{
		href: "https://ar.pinterest.com/",
		media: "pinterest",
		icon: "/icon-pinterest.svg",
	},
	{
		href: "https://www.instagram.com/",
		media: "instagram",
		icon: "/icon-instagram.svg",
	},
];
const footerLinks: { path: string; label: string }[] = [
	{ path: "/", label: "About Us" },
	{ path: "/", label: "Contact" },
	{ path: "/", label: "Blog" },
	{ path: "/", label: "Careers" },
	{ path: "/", label: "Support" },
	{ path: "/", label: "Privacy Policy" },
];

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={font.className}
				style={{ display: "flex", flexDirection: "column", minHeight: "110vh" }}
			>
				<NavBar logo="/logo.svg" alt="easybank-logo" />
				<h1 className="clipped">Easybank</h1>
				{children}
				<Footer
					logo="/logo-invert.svg"
					alt="easybank-logo"
					socialMedia={socialMedia}
					links={footerLinks}
				/>
			</body>
		</html>
	);
}
